TPO_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.views.static import serve
from django.conf import settings


urlpatterns = [
    path('', views.index, name= "index"),
    # Authentication
    path('register/', views.register_page, name= "register_page"),
    path('login/', views.login_request, name='login'),
    path('logout/', views.logout_request, name='logout'),
    
    path('TPO_app/', views.register_student, name= "register_student"),
    path('register_job/', views.register_job, name= "register_job"),
    path('register_student_submit/', views.register_student_submit, name= "register_student_submit"),
    path('companies/', views.companies, name= "companies"),
    path('upcoming_events/', views.upcoming_events, name= "upcoming_events"),
    path('upcoming_events_submit/', views.upcoming_events_submit, name= "upcoming_events_submit"),
    path('Statistics/', views.Statistics, name= "Statistics"),
    path('update_details/', views.update_details, name= "update_details"),
    path('update_user_details/', views.update_user_details, name= "update_user_details"),
    path('fill_details/', views.fill_details, name= "fill_details"),
    path('download/(?P<path>.*)$', serve,{'document_root':settings.MEDIA_ROOT}),
    
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TPO_website/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('TPO_app.urls')),
    path('', include("django.contrib.auth.urls")),
    path('company/', include(('company.urls', 'company'), namespace='company')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

company/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.views.static import serve
from django.conf import settings
from . import views

urlpatterns=[
    path('', views.companyindex, name='companyindex'),
    path('update_company_details/', views.update_company_details, name='update_company_details'),
    path('save_company_details/', views.save_company_details, name='save_company_details'),
    path('stats/', views.stats, name='stats'),
    path('download/(?P<path>.*)$', serve,{'document_root':settings.MEDIA_ROOT}),
    path('recieved_applications/', views.recieved_applications, name='recieved_applications'),
    path('logout/', views.logout, name='logout'),
    path('upload_result', views.upload_result, name='upload_result'),
    path('save_result', views.save_result, name='save_result'),
    path('delete', views.delete, name='delete'),
    path('confirm_delete', views.confirm_delete, name='confirm_delete'),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

company/models.py
from django.core.exceptions import ValidationError
from django.db import models
from TPO_app.models import CompanyLogin

# Create your models here.
class CompanyInfo(models.Model):
    username = models.CharField(max_length=200, primary_key=True, default='')
    cname = models.CharField(max_length=200)
    role = models.CharField(max_length=200)
    application = models.CharField(max_length=10, default='yes')
    date = models.CharField(max_length=100)
    salary = models.CharField(max_length=200)
    brochure = models.FileField(null=True)

    def __str__(self):
        return self.cname

class SelectedInfo(models.Model):
    username = models.CharField(max_length=200, primary_key=True, default='')
    cname = models.CharField(max_length=200)
    role = models.CharField(max_length=200)
    date = models.CharField(max_length=100)
    salary = models.CharField(max_length=200)
    result = models.FileField(null=True)

    def __str__(self):
        return self.cname

company/views.py
import datetime
import json
import urllib

from django.shortcuts import render,redirect,reverse
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password, check_password
from .models import CompanyInfo, SelectedInfo
from TPO_app.models import JobInfo, StudentInfo, CompanyLogin, highlight
from TPO_website import settings
from django.contrib import messages
import os
from django.conf import settings
from django.http import HttpResponse, Http404
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist

def companyindex(request):
    try:
        if request.session['userid']:
            name = request.session.get('userid')
            li = highlight.objects.all()
            return render(request,'companyindex.html', {'name':name, 'li':li})
        else:
            return redirect('login')
    except KeyError:
        return redirect('login')

def logout(request):
    try:
        del request.session['userid']
        messages.success(request, "You were successfully logged out.")
        return redirect('login')
    except KeyError:
        return redirect('login')

def stats(request):
    try:
        if request.session['userid']:
            name = request.session.get('userid')
            return render(request,'stats.html', {'name':name})
        else:
            return redirect('login')
    except KeyError:
        return redirect('login')

def update_company_details(request):
    try:
        if request.session['userid']:
            name = request.session.get('userid')
            try:
                form = CompanyInfo.objects.get(username=name);
                if form is not None:
                    return render(request, 'update_company_details.html', {'form': form, 'name':name})
                else:
                    return render(request, 'update_company_details.html', {'name':name})
            except ObjectDoesNotExist:
                return render(request, 'update_company_details.html', {'name':name})
        else:
            return redirect('login')
    except KeyError:
        return redirect('login')


def save_company_details(request):
    try:
        if request.session['userid']:
            username = request.session.get('userid')
            print(username)
            cname = request.POST['cname']
            role = request.POST['role']
            salary = request.POST['salary']
            date = request.POST['date']
            brochure = request.FILES['brochure']
            application = request.POST['application']
            Company_Info = CompanyInfo(username=username, cname=cname, role=role, application=application, date=date, salary=salary, brochure=brochure)
            Company_Info.save()
            messages.success(request, 'Your Details were successfully saved.')
            name = username
            return render(request, 'update_company_details.html',{'name':name})
        else:
            return redirect('login')
    except KeyError:
        return redirect('login')

def download(request, path):
    file_path = os.path.join(settings.MEDIA_ROOT, path)
    if os.path.exists(file_path):
        with open(file_path, 'rb') as fh:
            response = HttpResponse(fh.read(), content_type="application/adminupload")
            response['Content-Disposition'] = 'inline; filename=' + os.path.basename(file_path)
            return response
    raise Http404

def recieved_applications(request):
    try:
        if request.session['userid']:
            name = request.session.get('userid')
            ap = JobInfo.objects.filter(cname = name).values_list('uname', flat=True)
            l=[]
            for a in ap:
                l.append(StudentInfo.objects.get(uname = a))
            return render(request, 'recieved_applications.html',{'name':name, 'l':l})
        else:
            return redirect('login')
    except KeyError:
        return redirect('login')


def upload_result(request):
    try:
        if request.session['userid']:
            name = request.session.get('userid')
            return render(request, 'upload_result.html',{'name':name})
        else:
            return redirect('login')
    except KeyError:
        return redirect('login')

def delete(request):
    try:
        if request.session['userid']:
            name = request.session.get('userid')
            return render(request, 'delete.html',{'name':name})
        else:
            return redirect('login')
    except KeyError:
        return redirect('login')

def confirm_delete(request):
    try:
        if request.session['userid']:
            name = request.session.get('userid')
            password = request.POST['password']
            try:
                v = CompanyLogin.objects.get(username=name)
                b = check_password(password, v.password)
                print(b)
                if b is True:
                    li = CompanyInfo.objects.filter(username=name)
                    li.delete()
                    print('company info deleted')
                    si = SelectedInfo.objects.filter(username=name)
                    si.delete()
                    print('selected info deleted')
                    mi = JobInfo.objects.filter(cname=name)
                    mi.delete()
                    print('Job info deleted')
                    ni = CompanyLogin.objects.filter(username=name)
                    ni.delete()
                    print('Company login deleted')
                    user = User.objects.filter(username=name)
                    user.delete()
                    print('User info deleted')
                    del request.session['userid']
                    messages.success(request, "Account was successfully deleted.")
                    return redirect('login')
                else:
                    messages.warning(request, 'Incorrect Password')
                    return render(request, 'delete.html', {'name': name})
            except ObjectDoesNotExist:
                messages.warning(request, 'Invalid User')
                return redirect('login')
        else:
            return redirect('login')
    except KeyError:
        return redirect('login')


def save_result(request):
    try:
        if request.session['userid']:
            name = request.session.get('userid')
            li = CompanyInfo.objects.get(username=name)
            result = request.FILES['result']
            cname = li.cname
            role = li.role
            salary = li.salary
            date = datetime.datetime.now().strftime('%d/%m/%Y')
            li = SelectedInfo(username=name, result=result, cname=cname, role=role, salary=salary, date=date)
            li.save()
            messages.success(request, "Result was successfully uploaded.")
            return render(request, 'upload_result.html',{'name':name})
        else:
            return redirect('login')
    except KeyError:
        return redirect('login')

company/templates/delete.html
{% extends "companyindex.html" %}


{% load bulma_tags %}
{% load static %}
<link href="{% static '/css/styles.css' %}" rel="stylesheet">
<title>{% block title%}Applications Recieved{% endblock %}</title>
{% block content %}
<br>
<br>
<h1 class="title">Delete Account</h1>
<div class="tile is-parent">
    <div class="tile is-child box">
<form action="{% url 'company:confirm_delete' %}" method="POST">
                {% csrf_token %}

                <div class="field">
                    <label class="label">Enter Password</label>
                    <div class="control">
                        <input class="input " type="password" placeholder="" name="password" required style="width:30em; border:1px solid;">
                    </div>
                </div>

                <button type="submit" class="button is-primary is-danger" style="background-color:#f70000;" onclick="return confirm('Are you sure you want to delete the account  ?')"><strong>CONFIRM</strong></button>
</form>
        </div>
</div>
        {% include 'includes/messages.html' %}
            {% endblock %}

company/templates/navbar2.html
{% load static %}
<style>
.navbar-start .navbar-item:hover
{
    background-color:rgba(146, 165, 49, 0.81);
    color:white;
}
.header
{
    background-color:rgba(146, 165, 49, 0.81);
    color:white;
    height:12.5vh;
    width:100%;
    border: 2px solid transparent;
}
.header img
{
    margin-top:4px;
    margin-left:10px;
}
.header p
{
font-size:2vw;
//margin-top:1px;
margin-left:105px;
font-family:serif;
text-transform:uppercase;
word-spacing:7px;
padding:5px;
letter-spacing:0px;
}

.header h2
{
margin-left:115px;
margin-top:-2px;
//font-family:serif;
//text-transform:uppercase;
}
@media only screen and (max-width:768px)
{
.header
{
    height:20vh;
    width:100%;
    border: 2px solid transparent;
}
.header img
{
    margin-top:10px;
    margin-left:10px;
}
.header p
{
font-size:2vh;
margin-top:12px;
margin-left:120px;
font-family:serif;
text-transform:uppercase;
word-spacing:7px;
padding:5px;
letter-spacing:0px;
}

.header h2
{
margin-left:130px;
font-size:1.5vh;
}
}
</style>
<div class="header">
    <div>
        <img src="{% static 'images/KNITlogo.png' %}" height="82vh" width="82vh" style="float:left;"/>
    </div>
    <p >Training and Placement Management Portal</p>
    <h2>Kamla Nehru Institute of Technology, Sultanpur</h2>
</div>
<nav class="navbar" role="navigation" aria-label="main navigation" style="position: -webkit-sticky; position: sticky; top: 0;">
    <div class="navbar-brand">
        <a class="navbar-item" href="">
            <!-- <img src="" width="112" height="28"> -->
        </a>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
            <a class="navbar-item" href="{% url 'company:companyindex' %}" >
                <strong>Home</strong>
            </a>
            <a class="navbar-item" href="{% url 'company:stats' %}" >
                <strong>Stats</strong>
            </a>
            <a class="navbar-item" href="{% url 'company:update_company_details' %}">
                <strong>Update Details</strong>
            </a>
            <a class="navbar-item" href="{% url 'company:recieved_applications' %}">
                <strong>Recieved Applications</strong>
           </a>
            <a class="navbar-item" href="{% url 'company:upload_result' %}">
                <strong>Upload Result</strong>
            </a>
            <a class="navbar-item" href="{% url 'company:delete' %}">
                <strong>Delete account</strong>
            </a>

    </div>

        <div class="navbar-end">
            <div class="navbar-item">
                <div class="buttons" style="margin-right:20px;">
                    <a class="button is-primary is-light " href="{% url 'company:update_company_details' %}" style="background-color:rgba(146, 165, 49, 0.81);">
                    <strong style="color:white;"><i class="fa fa-user" aria-hidden="true" "></i> {{name}}</strong>
                    </a>
                    <a class="button is-light" href="{% url 'company:logout' %}">
                        <strong>Log out</strong>
                    </a>
                </div>
    </div>
</nav>

company/templates/recieved_applications.html
{% extends "companyindex.html" %}


{% load bulma_tags %}
{% load static %}
<link href="{% static '/css/styles.css' %}" rel="stylesheet">
<title>{% block title%}Applications Recieved{% endblock %}</title>
{% block content %}
<br>
<br>
<h1 class="title">APPLICATIONS RECIEVED</h1>

<div class="tile is-ancestor mt-6" style="display:flex; flex-wrap:wrap; justify-content:space-around;">
                        {% for li in l %}
                        <div class="card mx-4" style="margin:20px;">
                            <div class="card-content">
                                <div class="content">
                                    <p>Name: <strong>{{ li.fname }}</strong> </p>
                                    <p>Email: <strong>{{ li.email }}</strong></p>
                                    <p>Phone No.: <strong>{{ li.phoneno }}</strong></p>
                                    <p>CGPA: <strong>{{ li.cgpa }}</strong></p>
                                    <p>Class 10th percentage: <strong>{{ li.tenth }}</strong></p>
                                    <p>Class 12th percentage: <strong>{{ li.twelth }}</strong></p>
                                     <div class="file has-name">
                                    <a href="{{ li.resume.url }}" download="{{ li.resume.url }}"><button class="button is-light is-outlined is-pulled-right"><label class="file-label">
                                        <span class="file-cta">
                                            <span class="file-icon">
                                                <i class="fas fa-download"></i>
                                            </span>
                                            <span class="file-label">
                                                Download Resume
                                            </span>
                                        </span>
                                    </label></button></a>
                                </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
    </div>


        {% include 'includes/messages.html' %}
            {% endblock %}

company/templates/stats.html
{% extends "companyindex.html" %}
{% include 'includes/messages.html' %}

{% load bulma_tags %}
{% load static %}
<link href="{% static '/css/styles.css' %}" rel="stylesheet">
<title>{% block title%}Statistics{% endblock %}</title>
{% block content %}
<br>
<h1 class="title has-text-centered">Companies Recruiting</h1>
<div class="tile is-ancestor">
    <div class="tile is-6 is-vertical is-parent">
        <div class="tile is-child box">
            <canvas id="horizontalBarChartCanvas"></canvas>
        </div>
    </div>
    <div class="tile is-parent">
        <div class="tile is-child box">
            <p class="title has-text-centered">Highest & Average Package </p>
            <div>
                <canvas id="barChart"></canvas>
            </div>
        </div>
    </div>
</div>
<div class="field is-grouped is-pulled-right">
    <p class="control">
        <a href="{% static 'images/Placement2016-17.docx' %}" download>
        
            <button class="button is-light " style="background-color: rgba(105, 0, 255, 0.11);color: #6900FF;">
                <strong>
    
                    Placement Report 2016-17
                </strong>
            </button>
        </a>
    </p>
    <p class="control">
        <a href="{% static 'images/Placement2017-18.docx' %}" download>
        
            <button class="button is-primary is-light">
                <strong>
    
                    Placement Report 2017-18
                </strong>
    
            </button>
        </a>

    </p>
    <p class="control">
        <a href="{% static 'images/Placement2018-19.docx' %}" download>
        
            <button class="button is-danger is-light">
                <strong>
    
                    Placement Report 2018-19
                </strong>
    
            </button>
        </a>
    </p>
</div><br>
<script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.bundle.js'></script><br>
<section class="section">
    <div class="container has-text-centered">
        <h1 class="title">
            STATISTICS
        </h1>
        <br>
    </div>
    <div class="tabs is-fullwidth is-toggle ">
        <div class="container">
            <ul>
                <li class="tab is-active" onclick="openTab(event,'WebDev')"><a>2019-20</a></li>
                <li class="tab" onclick="openTab(event,'WebAud')"><a>2018-19</a></li>
                <li class="tab" onclick="openTab(event,'Support')"><a>2017-18</a></li>
            </ul>
        </div>
    </div>
</section>
<div class="container section ml-6">
    <div id="WebDev" class="content-tab">
        <div class="columns is-mobile">
            <div class="column">BRANCHES</div>
            <div class="column">TOTAL</div>
            <div class="column">PLACED</div>
            <div class="column">PERCENTAGE</div>
        </div>
        <div class="columns is-mobile">
            <div class="column is-size-4">CS</div>
            <div class="column title" data-count="290">0</div>
            <div class="column title" data-count="270">0</div>
            <div class="column title" data-count="93">0</div>
        </div>
        <div class="columns is-mobile">
            <div class="column is-size-4">IT</div>
            <div class="column title" data-count="350">0</div>
            <div class="column title" data-count="320">0</div>
            <div class="column title" data-count="91">0</div>
        </div>
        <div class="columns is-mobile">
            <div class="column is-size-4">EXTC</div>
            <div class="column title" data-count="150">0</div>
            <div class="column title" data-count="95">0</div>
            <div class="column title" data-count="63">0</div>
        </div>
    </div>
    <div id="WebAud" class="content-tab" style="display:none">
        <div class="columns is-mobile">
            <div class="column">BRANCHES</div>
            <div class="column">TOTAL</div>
            <div class="column">PLACED</div>
            <div class="column">PERCENTAGE</div>
        </div>
        <div class="columns is-mobile">
            <div class="column is-size-4">CS</div>
            <div class="column title" data-count="260">0</div>
            <div class="column title" data-count="210">0</div>
            <div class="column title" data-count="81">0</div>
        </div>
        <div class="columns is-mobile">
            <div class="column is-size-4">IT</div>
            <div class="column title" data-count="380">0</div>
            <div class="column title" data-count="310">0</div>
            <div class="column title" data-count="81">0</div>
        </div>
        <div class="columns is-mobile">
            <div class="column is-size-4">EXTC</div>
            <div class="column title" data-count="110">0</div>
            <div class="column title" data-count="90">0</div>
            <div class="column title" data-count="81">0</div>
        </div>
    </div>
    <div id="Support" class="content-tab" style="display:none">
        <div class="columns is-mobile">
            <div class="column">BRANCHES</div>
            <div class="column">TOTAL</div>
            <div class="column">PLACED</div>
            <div class="column">PERCENTAGE</div>
        </div>
        <div class="columns is-mobile">
            <div class="column is-size-4">CS</div>
            <div class="column title" data-count="200">0</div>
            <div class="column title" data-count="140">0</div>
            <div class="column title" data-count="70">0</div>
        </div>
        <div class="columns is-mobile">
            <div class="column is-size-4">IT</div>
            <div class="column title" data-count="260">0</div>
            <div class="column title" data-count="220">0</div>
            <div class="column title" data-count="85">0</div>
        </div>
        <div class="columns is-mobile">
            <div class="column is-size-4">EXTC</div>
            <div class="column title" data-count="170">0</div>
            <div class="column title" data-count="140">0</div>
            <div class="column title" data-count="82">0</div>
        </div>
    </div>

    </section>
    <script src="{% static 'js/counter2.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
        integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
        crossorigin="anonymous"></script>
    <script src="{% static 'js/Chart.js' %}"></script>
    <script src="{% static 'js/ChartHorizontal.js' %}"></script>


    {% endblock %}

company/templates/update_company_details.html
{% extends "companyindex.html" %}

{% load bulma_tags %}
{% load static %}
<link href="{% static '/css/styles.css' %}" rel="stylesheet">
<title>{% block title%}Update Company Details{% endblock %}</title>
{% block content %}
<br>
<div class="tile is-ancestor">
    <div class="tile is-6 is-vertical is-parent">
        <div class="tile is-child box">
            <figure class="image is-4by3">
                <img src="{% static 'images/register_student.svg'%}" alt="Event 1">
            </figure>
        </div>
    </div>
    <div class="tile is-parent">
        <div class="tile is-child box">
            <p class="title">Update Company Details:</p>
            <form action="{% url 'company:save_company_details' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="field">
                    <label class="label">Company Name</label>
                    <div class="control">
                        <input class="input " type="text" placeholder="" value="{{ form.cname }}" name="cname" required>
                    </div>
                </div>
                <div class="field">
                    <label class="label">Role</label>
                    <div class="control">
                        <input class="input" type="text" placeholder="" name="role" value="{{ form.role }}" required>
                    </div>
                </div><br>
                <div class="field">
                    <label class="label">Recieve Applications</label>
                    <div class="control">
                        {% if form.application == 'yes' %}
                        <input class="radio" type="radio" name="application" value="yes" checked>
                        <label>Yes</label>&nbsp &nbsp
                        <input class="radio" type="radio" name="application" value="no">
                        <label>No</label>
                        {% else %}
                        <input class="radio" type="radio" name="application" value="yes">
                        <label>Yes</label>&nbsp &nbsp
                        <input class="radio" type="radio" name="application" value="no" checked>
                        <label>No</label>
                        {% endif %}
                    </div>
                </div><br>
                <div class="field">
                    <label class="label">Last Application Date</label>
                    <div class="control">
                        <input class="input" type="date" placeholder="dd/mm/yyyy" name="date" value="{{ form.date }}" required>
                    </div>
                </div><br>
                <div class="field">
                    <label class="label">Salary</label>
                    <div class="control">
                        <input class="input" type="text" placeholder="" name="salary" value="{{ form.salary }}" required>
                    </div>
                </div><br>
                <div class="file has-name">
                    <label class="file-label">
                        <input class="file-input" type="file" name="brochure" value="{{ form.brochure }}" required>
                        <span class="file-cta">
                            <span class="file-icon">
                                <i class="fas fa-upload"></i>
                            </span>
                            <span class="file-label">
                                Choose a file…
                            </span>
                        </span>
                        <span class="file-name">
                            Brochure.pdf
                        </span>
                    </label>
                </div>
                <br>

                <button type="submit" class="button is-primary is-light"><strong>Save</strong></button>
            </form>
        </div>
    {% include 'includes/messages.html' %}
    </div>
</div>
{% endblock %}

company/templates/upload_result.html
{% extends "companyindex.html" %}

{% load bulma_tags %}
{% load static %}
<link href="{% static '/css/styles.css' %}" rel="stylesheet">
<title>{% block title%}Upload Result{% endblock %}</title>
<style>
    input[type=file] {
  display: none
}

.choosefile, .fileuploadspan {
  font-family: "Comic Sans MS"
}
</style>
{% block content %}
<br>
<div class="tile is-ancestor">
    <div class="tile is-parent">
        <div class="tile is-child box">
            <p class="title">Upload Result:</p>
            <form action="{% url 'company:save_result' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <br>
                <div class="file has-name">
                    <label class="file-label">
                        <input class="file-input" id="fileInput" type="file" name="result" value="{{ form.brochure }}" required>
                        <span class="file-cta">
                            <span class="file-icon">
                                <i class="fas fa-upload"></i>
                            </span>
                            <span class="file-label">
                                Choose a file…
                            </span>
                        </span>
                        <span class="file-name" id="fileuploadspan">
                            Result.pdf
                        </span>
                    </label>
                </div>
                <br>
                <button type="submit" class="button is-primary is-light"><strong>Upload</strong></button>
            </form>
        </div>
    {% include 'includes/messages.html' %}
    </div>
</div>
<script>

$('#fileInput').change(function(e) {
  var filename = this.files[0].name;
  $('#fileuploadspan').innerHTML(filename);
});
</script>
{% endblock %}